language: node_js

sudo: false

node_js:
  - "10.9"

branches:
  only:
    - master
  
addons:
  chrome: stable

notifications:
  email:
    recipients:
      - marcio.hsdl@gmail.com
    on_success: always
    on_failure: always

before_script:
  - npm install -g @angular/cli

script:
  - ng build --prod
  - npm run lint